### ISSUE TITLE
Bind and asyncBind (Thank you!)

### ISSUE THREAD

**Issue by jacobaraujo7** [SandroMaglione/fpdart#1]
We need to add an Either.bind and Either.asyncBind that takes another Either (or Future<Either>) processing the result of R, without neglecting the result of L.

Thanks for documenting the concepts of functional programming, which dartz unfortunately still fails to do. I hope I can help with a PR solving this issue soon. Hugs!

**Comment by SandroMaglione** [comment]
Hi @jacobaraujo7 

Thanks for the support and the suggestion 🙏

I am currently working on the core types and also on expanding the documentation to make the package accessible to as many people as possible. Meanwhile, we can collect every usecase or method that we can later add to the package. Any PR is welcome 😁

**Comment by SandroMaglione** [comment]
#2 👍
