### ISSUE TITLE
Llinks are not working 

### ISSUE THREAD

**Issue by rabinacharya11** [SandroMaglione/fpdart#107]
When ever Clicked on the tutorial link in the readme file 
Non of these links work!  

Reference : [View](https://pub.dev/packages/fpdart) 

<img width="590" alt="Screen Shot 2023-05-12 at 00 03 18" src="https://github.com/SandroMaglione/fpdart/assets/72679799/d08e6b9e-9376-4032-a3d2-23ca78cb56c6">

This is what is thrown! 

<img width="519" alt="Screen Shot 2023-05-12 at 00 01 31" src="https://github.com/SandroMaglione/fpdart/assets/72679799/de519fcc-a4cd-496a-bbf5-d89392dbdd03">

**Comment by SandroMaglione** [comment]
@rabinacharya11 fixed now, it was an issue with the source link

Thanks for reporting 🙏🏼
