### ISSUE TITLE
DISCUSSION : Extension

### ISSUE THREAD

**Issue by wer-mathurin** [SandroMaglione/fpdart#126]
We added this extension in our project and just sharing it:

extension FlatMapOnNull<L, R> on TaskEither<L, R?> {
  TaskEither<L, R> flatMapOnNull(L left) {
    return flatMap(
        (r) => r != null ? TaskEither.right(r) : TaskEither.left(left));
  }
}

@SandroMaglione : Do you see value adding this to the library?

**Comment by SandroMaglione** [comment]
Hi @wer-mathurin,

I generally would avoid expanding too much the core API. In which situations are you using this? How often is this needed in your opinion?
