### ISSUE TITLE
Mockito can't generate stubs for functions returning Either

### ISSUE THREAD

**Issue by bekaIva** [SandroMaglione/fpdart#130]
Mockito can't generate stubs for functions returning Either in version 1.1.0.
Mockito was generating _FakeEither implementing with Either, which can't do after version 1.1.0 because Either is market as sealed now.
`class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}
`

**Comment by SandroMaglione** [comment]
Hi @bekaIva 

This may be related to #123

**Comment by dJani97** [comment]
Same here, does Either have to be sealed for sure? This makes them really hard to test.
