### ISSUE TITLE
Export fpdart package conflict with State of material.

### ISSUE THREAD

**Issue by phalsopheak** [SandroMaglione/fpdart#138]
I build my core private package that use fpdart. So i export fpdart with my package to use later.
The problem is, It conflict with State of material library.

**Comment by SandroMaglione** [comment]
Hi @phalsopheak 

You can take a look at the [managing_imports](https://github.com/SandroMaglione/fpdart/tree/main/examples/managing_imports) example ([export with `hide State`](https://github.com/SandroMaglione/fpdart/blob/main/examples/managing_imports/lib/functional.dart))

**Comment by phalsopheak** [comment]
Yeah I did.
Just want to let you know if you can change the name is better.
