### ISSUE TITLE
TaskEither from predicate should accept a FutureOr.

### ISSUE THREAD

**Issue by zellidev0** [SandroMaglione/fpdart#143]
I would like to use the `TaskEither` from predicate with a `async` predicate.
I think this would fit into the TaskEither constructor very well.
The current implementation is this.
```dart
factory TaskEither.fromPredicate(
          R value, bool Function(R a) predicate, L Function(R a) onFalse) =>
      TaskEither(
          () async => predicate(value) ? Right(value) : Left(onFalse(value)));
```
It could be changed like so:
```dart
factory TaskEither.fromPredicate(
  R value, 
  FutureOr<bool> Function(R a) predicate, 
  L Function(R a) onFalse
) => TaskEither(
  () async {
    final result = await predicate(value);
    return result ? Right(value) : Left(onFalse(value));
  }
);
```

Would this be a good idea? If so I can submit a PR.

**Comment by SandroMaglione** [comment]
Hi @zellidev0 

`TaskEither.fromPredicate` is intended for sync conditions, so I would keep the current implementation. For async conditions I would suggest first performing the async operation, and then chaining a function to check the result.

Let me know if you had some specific example where this would not work
