### ISSUE TITLE
Help converting error types

### ISSUE THREAD

**Issue by berbsd** [SandroMaglione/fpdart#145]
I’m struggling to see how I can convert from one error type to another. 

I have a function that returns a TaskEither<ApiError, Client>. I want to use the resulting client in another function that returns a TaskEither<ServiceError, String> . The two error types are not sharing a common base class. 

I tried to chain the calls but could not make it work.  The code is something along these lines. Also tried to add a mapLeft but did not work either. I have been going in circles and any help would be greatly appreciated.

 The library is awesome, but would love to see more examples for common use-cases. 

```dart
TaskEither<ServiceError, String> apiCall(URI uri) {
  
  return getClient()
      .mapLeft((error) => ServiceError.mapError(error))
      .flatMap((client) => TaskEither.tryCatch(
                () async => client.get(uri),
                ServiceError.mapError
              ).chainEither( // …. Remaining code to parse response

}

// the signature for getClient is as follow

TaskEither<ApiError, String> getClient() {
 …
}

```

**Comment by SandroMaglione** [comment]
Hi @berbsd 

How is `ServiceError.mapError` defined?

`mapLeft((error) => ServiceError.mapError(error))` should convert `ApiError` to `ServiceError` for this to work, for example:

```dart
class ServiceError {
  ServiceError();
  factory ServiceError.mapError(ApiError error) => ServiceError();
}
```

The second `ServiceError.mapError` inside `tryCatch` cannot have the same signature, since the error in `tryCatch` gives you `Object` + `StackTrace` instead of `ApiError`.

If for example you refactor like below it compiles:

```dart
typedef URI = String;

class ServiceError {
  ServiceError();
  factory ServiceError.mapError(ApiError error) => ServiceError();
}

class ApiError {}

TaskEither<ApiError, String> getClient = TaskEither.of("");
TaskEither<ServiceError, String> apiCall(URI uri) {
  return getClient
      .mapLeft(
        (error) => ServiceError.mapError(error),
      )
      .flatMap(
        (client) => TaskEither.tryCatch(
          () async => client + "",
          (_, __) => ServiceError(),
        ),
      );
}
```

Let me know if you have any question
