### ISSUE TITLE
[Question] Any side effect function in TaskEither or Either?

### ISSUE THREAD

**Issue by samuelyung** [SandroMaglione/fpdart#146]
Hi, I come from Java (vavr) and for the side effect function I mean something like [peek()](https://www.javadoc.io/static/io.vavr/vavr/0.10.4/io/vavr/control/Either.html#peek-java.util.function.Consumer-), that is, just peek without changing `Right` if it's a `Right`, and for `Left` it is called `peekLeft()`.

Now I need to do something like this to simulate peek:

```
taskEither.map((right) {
  doSomething(right);
  return right;
})
```

**Comment by SandroMaglione** [comment]
Hi @samuelyung 

I think what you are looking for is [`chainFirst`](https://pub.dev/documentation/fpdart/latest/fpdart/TaskEither/chainFirst.html).

**Comment by samuelyung** [comment]
No...

`chainFirst()` requires a function argument having a return type of `TaskEither<L, C>`, while the [peek()](https://www.javadoc.io/static/io.vavr/vavr/0.10.4/io/vavr/control/Either.html#peek-java.util.function.Consumer-)'s [Consumer](https://docs.oracle.com/javase/8/docs/api/java/util/function/Consumer.html#accept-T-) argument doesn't return anything.
That is, it just "observe" the value.

**Comment by SandroMaglione** [comment]
You can return a `TaskEither` with return type as `void`. When `chainFirst` is executed the result is ignored, so in practice it works as if you are observing the value
