### ISSUE TITLE
Couldn't access https://www.sandromaglione.com

### ISSUE THREAD

**Issue by papakay** [SandroMaglione/fpdart#148]
I've been trying to access the resources on https://www.sandromaglione.com/ for several weeks now without any luck.

I initially I thought it was an issue with my internet service provider, I switched to a different provider and its same issue.

I've also tried with different browsers and still no luck.

<img width="576" alt="Screenshot 2024-04-11 at 4 32 15 AM" src="https://github.com/SandroMaglione/fpdart/assets/5013738/41171d4d-65c8-405c-bfb0-75a61633a76e">

Location is Nigeria.

Thanks.

**Comment by SandroMaglione** [comment]
Hi @papakay 

Not sure what’s happening here, the site should be up everywhere. Are you able to verify if the site works in some other network in your area?

Closing since this is not strictly related to fpdart, feel free to continue the discussions below
