### ISSUE TITLE
Shortcut for `Option.none()` don't work for me

### ISSUE THREAD

**Issue by eduardoflorence** [SandroMaglione/fpdart#15]
**Sample Code:**
```dart
import 'package:fpdart/fpdart.dart';

class Fp {
  Option<double> divide(double a, double b) {
    if (b == 0) {
      // return Option.none();
      return none();
    }
    return some(a / b);
  }
}

void main() {
  final fp = Fp();
  final value = fp.divide(8, 0);

  print(value.getOrElse(() => 2));
}
```

**Error:**
Unhandled exception:
type '() => double' is not a subtype of type '() => Never' of 'orElse'

**Solution:**
Replace `none()` with `Option.none()` in my code

or

In `fpdart-0.0.8/lib/src/option.dart`, line 22:
Replace:
`Option<T> none<T>() => const None();`
With:
`Option<T> none<T>() => None<T>();`

**Comment by SandroMaglione** [comment]
Hi @eduardoflorence 

Yes, I noticed this problem some time ago. I actually [fixed it in the last commit](https://github.com/SandroMaglione/fpdart/blob/6f7c67c2eca8cdff0735d1b4f9ebbb44a5911519/lib/src/option.dart#L22). Now it should work fine.
Thanks for pointing this out 😁
