### ISSUE TITLE
Confusing Documentation for foldLeft and foldRight Methods in Either Class

### ISSUE THREAD

**Issue by hanmango-o** [SandroMaglione/fpdart#152]
### Description

The `foldLeft` and `foldRight` methods in the ` either.dart ` have identical comments, which can be misleading because these methods perform different operations.

### Current Documentation

```dart
/// Return the result of `f` called with `b` and the value of [Right].
/// If this [Either] is [Left], return `b`.
@Override
C foldRight<C>(C b, C Function(C acc, R b) f);

/// Return the result of `f` called with `b` and the value of [Right].
/// If this [Either] is [Left], return `b`.
@Override
C foldLeft<C>(C b, C Function(C acc, R b) f) =>
    foldMap<Endo<C>>(dualEndoMonoid(), (b) => (C c) => f(c, b))(b);
```

### Issue

The comments for foldLeft and foldRight are identical, even though these methods should have different descriptions because they perform different operations:

* foldLeft: Folds the elements from left to right.

* foldRight: Folds the elements from right to left.

### Suggested Documentation

To avoid confusion, the comments should reflect the distinct behaviors of these methods.

```dart
/// This method folds the value from right to left.
/// 
/// Return the result of `f` called with `b` and the value of [Right].
/// If this [Either] is [Left], return `b`.
@Override
C foldRight<C>(C b, C Function(C acc, R b) f);

/// This method folds the value from left to right.
///
/// Return the result of `f` called with `b` and the value of [Right].
/// If this [Either] is [Left], return `b`.
@Override
C foldLeft<C>(C b, C Function(C acc, R b) f) =>
    foldMap<Endo<C>>(dualEndoMonoid(), (b) => (C c) => f(c, b))(b);
```

Thanks for your attention to this issue and for your continuous efforts. I always appreciate using this library!

**Comment by JRParreno** [comment]
bro do you have any idea how to get the right value only?
