### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by huzaifansari54** [SandroMaglione/fpdart#154]
Hi 👋 I recently used this pkg and love it I want to suggest that there is taskEeither handler which performs future tasks but in my project I need handler which handle streams, and can make some thing  which is not run on main isolate but on io isolate something like in kotlin a code which run on io threads not main threads  and thanks for this community work

**Comment by SandroMaglione** [comment]
Hey @huzaifansari54 

There is [an issue](https://github.com/SandroMaglione/fpdart/issues/27) for streams in fpdart, you can follow the progress there.
