### ISSUE TITLE
[v2] Completely fails to run anything

### ISSUE THREAD

**Issue by lishaduck** [SandroMaglione/fpdart#155]
SSCCE:

```dart
test('sscce', () async {
  final eff = Effect<Never, Object, String>.tryCatch(
    execute: () => '',
    onError: (e, __) => e,
  );
  await expectLater(eff.runFuture(), completes);
});
```

Fails with:

```console
Cause.Die(type '(Context<Never>) => FutureOr<Either<Cause<Object>, String>>' is not a subtype of type '(Context<Null>) => FutureOr<Either<Cause<Object>, String>>')
package:fpdart/src/effect.dart 786:7       ProvideNull.runFuture
test/some_file_somewhere_test.dart l:c  main.<fn>
```

↑ Diff: Context's generic is `Never` rather than `Null`.
Not sure why this is happening.

**Comment by lishaduck** [comment]
You have got to be kidding me! I just changed the context to Null, and it works fine. It should be Never, but it's a good workaround.

**Comment by SandroMaglione** [comment]
@lishaduck yes, you should use `Null`

This is related to how dart treats `Never` and type variance ([more info](https://github.com/dart-lang/language/issues/3670))
