### ISSUE TITLE
Predicate [feature request]

### ISSUE THREAD

**Issue by pihentagy** [SandroMaglione/fpdart#18]
Hi!

Any plans to support Predicate and composing predicates?

Predicate:
```dart
typedef Predicate<E> = bool Function(E element);
```

composition:
```dart
var Predicate<File> isEmpty;
var Predicate<File> modifiedToday;
files.where(isEmpty && modifiedToday);
```

**Comment by SandroMaglione** [comment]
Hi @pihentagy 

Could you please elaborate a little on what would you like `Predicate` to be? Could you explain the meaning and some usecase examples?

**Comment by pihentagy** [comment]
As in the example above, one can use it to combine simple predicates in `List.where()` clause (find all files, which are empty and modified today). In the meantime I figured out that `&&` is not overrideable, so the combinators would seem less natural (either `&` can be used for "and", `~` for "not", or can be solved with normal method names).

**Comment by SandroMaglione** [comment]
@pihentagy would you like fpdart to integrate some predefined predicates (like `isEmpty`, `modifiedToday`) or would you prefer just to have the `Predicate` type with some helper functions to make it composable?

**Comment by pihentagy** [comment]
`isEmpty` and `modifiedToday` are clearly out of scope for fdpart and too specific. From fpdart I just prefer to have `Predicate` type defined with some helpers to make it composable. As I can see, unfortunately dart core does not have this type (but I have seen it defined for internal use in dart core). And solving composability is not easy since the "natural" operators (`&&`, `||` and `!`) are not overrideable. I can provide a small patch for defining predicate and 2-3 methods for composition, but you have to decide if you support some kind of operator overloading (like [Moor](https://moor.simonbinder.eu/docs/getting-started/expressions/) as suggested in [this reddit post](https://www.reddit.com/r/dartlang/comments/ot87qw/operator_overloading/h6tzqtt/?context=3) or via normal methods).
