### ISSUE TITLE
Alt runs the Task/IO twice

### ISSUE THREAD

**Issue by TheOnlyNurse** [SandroMaglione/fpdart#21]
Due to how Alt is implemented, in TaskEither especially, it runs the Task twice.
```dart
TaskEither(() async => (await run()).match((_) => orElse().run(), (_) => run()))
```
It runs the code, matches and then returns the **unrun** code to the right (which will then be run once again by the user). Especially for stateful function chains this can be both difficult to diagnose (since there is no documentation saying that this is an intended effect) and undesirable in general (I've taken to side-stepping Alt completely). 

Here's a code snippet:
```dart
TaskEither(() async {
  print('running');
  return right(1);
}).alt(() {
  print('running alt');
  return TaskEither.right(2);
}).map((r) {
  print('done');
  return r;
}).run();
```
Here's what I get:
```console
I/flutter ( 8087): running
I/flutter ( 8087): running
I/flutter ( 8087): done
```

Am I missing something? Is this is way it's meant to function?

**Comment by SandroMaglione** [comment]
Hi @TheOnlyNurse 

Thanks for reporting this. Indeed, it was not correct since it was running twice the function. I fixed it now 🙏🏼

**Comment by TheOnlyNurse** [comment]
Thanks @SandroMaglione you're the best! I'll have a gander at the changes when I can.
