### ISSUE TITLE
Error when generating mock class

### ISSUE THREAD

**Issue by Alias3e** [SandroMaglione/fpdart#22]
I encountered the following errors while generating a mock repository which returns an Either object. That being said, it seems like that my test still runs fine. 

'Either.map3' ('Either<L, E> Function<C, D, E>(Either<L, C>, Either<L, D>, E Function(R, C, D))') isn't a valid concrete implementation of 'Either.map3' ('Either<L, E> Function<C, D, E>(Either<L, C>, Either<L, D>, E Function(R, C, D))').

'Either.map2' ('Either<L, D> Function<C, D>(Either<L, C>, D Function(R, C))') isn't a valid concrete implementation of 'Either.map2' ('Either<L, D> Function<C, D>(Either<L, C>, D Function(R, C))').

This was the class I was mocking

```
abstract class AuthRepository {
  Future<Either<Failure, User>> login({
    required String email,
    required String password,
  });
  Future<Either<Failure, Unit>> logout();
  Future<Either<Failure, Unit>> resetPassword(String email);
}
```

and this is the code generated by Mockito that giving me the compile time error.

```
import 'package:fpdart/fpdart.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}
```

For completeness this is the rest of the Mockito generated class.

```
/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> login(
          {String? email, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(#login, [], {#email: email, #password: password}),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.User>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> logout() =>
      (super.noSuchMethod(Invocation.method(#logout, []),
              returnValue: Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.Failure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> resetPassword(String? email) =>
      (super.noSuchMethod(Invocation.method(#resetPassword, [email]),
              returnValue: Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.Failure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
  @override
  String toString() => super.toString();
}
```

mockito: 5.0.15
fpdart: 0.0.10

**Comment by MrOnyszko** [comment]
This prevents me from using this awesome library :(

**Comment by MrOnyszko** [comment]
Instead of using [mockito]( https://pub.dev/packages/mockito) I migrated to [mocktail](https://pub.dev/packages/mocktail). I don't use Fakes for TaskEither any other functional type so far. I tried to write fake for it, but it gives the same issue. You could see usage in [planik-app](https://github.com/MrOnyszko/planik-app)
