### ISSUE TITLE
[QUESTION] What is the difference between Either and IOEither?

### ISSUE THREAD

**Issue by PTLam25** [SandroMaglione/fpdart#28]
I understand that **TaskEither** is for using for the result of the async function. 

But what is the difference between **Either** and **IOEither**? It seems like both of them is for sync result. When I should use Either and IOEither? Can I use only one of them?

**Comment by apiep** [comment]
May I try to answer?
IOEither are much like TaskEither

While Task represence an async side effect, IO represence sync side effect. So if TaskEither are Async Side Effect that can fail, IOEither are Sync Side Effect that can fail.

TaskEither are like Task<Either<L, R>> so do IOEither are IO<Either<L, R>>

**Comment by SandroMaglione** [comment]
> TaskEither are like Task<Either<L, R>> so do IOEither are IO<Either<L, R>>

@PTLam25 both `TaskEither` and `IOEither` are helper types for what @apiep mentioned. 

`Either` represents **the result** of a computation that can fail.

`IO` represents **the definition** of a sync computation **that never fails**.

`IOEither` brings together these two concepts, it is the definition of a computation that may fail. Basically, it is an `IO` that returns a `Either` (`IO<Either<L, R>>`).
