### ISSUE TITLE
[Question] is there any better way to combine two Reader<Deps1, Result1> and Reader<Deps2, Result2>?

### ISSUE THREAD

**Issue by apiep** [SandroMaglione/fpdart#29]
So, I have a function that return `Reader<Deps1, Task<bool>>` called `waitForAuthenticated()` and a second function that return `Reader<Deps2, Task<R>>` called `getSomething()`, is there a better way to compose both reader?

I have tried to use
```dart
var task1 = waitForAuthenticated().run(_deps1);
var task2 = getSomething().run(_deps2);

// ...
// At the outside part of my code / public facing API
task1(task2).run();
```

But then, I kind of "dislike" calling `.run()` method on reader as it make my reader not lazy now, is there a better way to do this without calling `.run()` method on my reader?

**Comment by SandroMaglione** [comment]
Hi @apiep 

Am I correct in assuming that you just want to execute `task1` and `task2` one after the other, without dependencies between the two?

In that case you can use [`local`](https://github.com/SandroMaglione/fpdart/blob/5b4786ec7d95ce79b535564a814a49fef63fd440/lib/src/reader.dart#L65) to change the context from `Deps1` to `Deps2`:

```dart
import 'package:fpdart/fpdart.dart';

class Deps1 {
  final String dep;
  const Deps1(this.dep);
}

class Deps2 {
  final String dep;
  const Deps2(this.dep);
}

Reader<Deps1, Task<bool>> waitForAuthenticated() => Reader(
      (deps1) {
        print('Execute waitForAuthenticated: ${deps1.dep}');
        return Task.of(true);
      },
    );

Reader<Deps2, Task<String>> getSomething() => Reader(
      (deps2) {
        print('Execute getSomething: ${deps2.dep}');
        return Task.of("");
      },
    );

void main() async {
  const _deps1 = Deps1('I am Deps1');
  const _deps2 = Deps2('I am Deps2');
  final pipe = waitForAuthenticated()
      .local<Deps2>(constF(_deps1))
      .andThen(getSomething)
      .run(_deps2);

  final result = await pipe.run();
}
```

This code chains the calls to `waitForAuthenticated` and `getSomething` by calling them one after the other. The result is the following:

```
Execute waitForAuthenticated: I am Deps1
Execute getSomething: I am Deps2
```

Is this what you where looking for?

**Comment by apiep** [comment]
Yes it is something like that, that I wanted. Thank you :)

I noticed `local` method before, but because it has a parameter with it, that's the part what confuse me
