### ISSUE TITLE
Tuple2 `map` and `mapSecond`

### ISSUE THREAD

**Issue by evandrmb** [SandroMaglione/fpdart#30]
Hi, I'm curious about why `map` and `mapSecond` behave exactly the same (according to docs). Shouldn't `map` allow users to change the type of both values in `Tuple2`?

I'm currently using version `0.0.12`

**Comment by SandroMaglione** [comment]
Hi @evandrmb 

The `map` method is an `override` of [Functor2](https://github.com/SandroMaglione/fpdart/blob/ef7dea5fb89ed69d4c9ae5bdf963c2a40eaadbc5/lib/src/typeclass/functor.dart#L11), this means that the type signature of the method is expected to be the same. For this reason, `map` is allowed to update only one value.

Nonetheless, I added a `mapBoth` method for this purpose.

Thanks for the feedback 👍
