### ISSUE TITLE
Missing fold method for Option

### ISSUE THREAD

**Issue by alfalcon90** [SandroMaglione/fpdart#45]
I'm trying to migrate from dartz to fpdart and I noticed that `Option` has `foldLeft` and `foldRight` but doesn't have a `fold` method. `Either` has all three, though. They both have `match` which is the same as `fold`, any reason we have `match`?

Thanks for your work on this. I appreciate the great documentation.

**Comment by SandroMaglione** [comment]
Hi @alfalcon90,

fpdart initially had only `match`. Then `fold` was [added to `Either` to ease the migration from `dartz`](https://github.com/SandroMaglione/fpdart/pull/2), so now we have both `fold` and `match`. `fold` was not added to `Option`, so we only have one method `match`.

Let me know if you this is clear and if you have any suggestions on this
