### ISSUE TITLE
Question about TaskEither.tryCatch

### ISSUE THREAD

**Issue by TheHypnoo** [SandroMaglione/fpdart#50]
Hello, I have a question, as I am quite new to Functional programming.

In this case I am using `TaskEither.tryCatch` 

Example: 
```
TaskEither.tryCatch(() async {
      final Response getPrice = await post(
        Uri.parse(
            "URL"),
        headers: {
          'Content-Type': 'application/json; charset=UTF-8',
        },
      );
      final Map<String, dynamic> json =
          jsonDecode(getPrice.body) as Map<String, dynamic>;

      if (!json.containsKey("pricing")) {
        throw Exception("I don't have price");
      }
      return json["pricing"].toString();
    }, (error, stackTrace) {
      error.log();
      return error.toString();
    });
```
In this case if I do a throw, it still returns the function as correct, I don't know if there is no way using the TryCatch or exactly how it works?

Thanks!!

**Comment by TheHypnoo** [comment]
Sorry, I have already found the problem, the throw did work, only if the post did not work it still returned me as correct.

**Comment by SandroMaglione** [comment]
Hi @TheHypnoo 

Thanks for the example 🙏🏼. I wrote a [full blog post](https://www.sandromaglione.com/techblog/fpdart-api-request-with-validation-functional-programming) based on your example to explain how `TaskEither` and API requests work in `fpdart`.

Let me know if you need any further clarification 👍
