### ISSUE TITLE
How to write the `finally` process  in TaskEither.tryCatch

### ISSUE THREAD

**Issue by utamori** [SandroMaglione/fpdart#51]
How can I describe the common process that I want to do finally in TaskEither.tryCatch?

**Comment by SandroMaglione** [comment]
Hi @utamori 

The mental model in functional programming is a little different.

Using `TaskEither.tryCatch` you can run an **async** function, catch **any** error, and convert the result to an `Either`. `tryCatch` is not trying to map 1-1 to try/catch/finally.

That being said, if you want to run a `finally` in fpdart you need to chain a `Task` to `TaskEither`:
1. Execute the `TaskEither` using `match`
2. Chain a `Task` (using for example `chainFirst`) that runs in any case (i.e. `finally`) after `TaskEither`

```dart
import 'package:fpdart/fpdart.dart';

Future<int> apiRequestMock() => Future.value(10);

/// Imperative code
///
/// `try` - `catch` - `finally`
Future<void> imperative() async {
  try {
    final response = await apiRequestMock();
    print(response);
  } catch (e) {
    print("Error: $e");
  } finally {
    print("Complete!");
  }
}

/// Functional code
///
/// `tryCatch`
Future<void> functional() async {
  final task = TaskEither.tryCatch(
    apiRequestMock,
    (e, _) => "Error: $e",
  ).match<Unit>(
    (l) {
      print(l);
      return unit;
    },
    (r) {
      print(r);
      return unit;
    },
  ).chainFirst<Unit>(
    (a) => Task(
      () async {
        print("Complete!");
        return unit;
      },
    ),
  );

  task.run();
}
```

Let me know if this makes sense. Feel free to ask for any further clarification.

***

I add the complete example inside the [example folder](https://github.com/SandroMaglione/fpdart/blob/main/example/src/task_either/finally.dart).
