### ISSUE TITLE
Consider switching Option.match parameter order?

### ISSUE THREAD

**Issue by marroen** [SandroMaglione/fpdart#52]
This is only a matter of personal preference, but here's my reasoning:
You routinely handle Eithers first with onLeft, then onRight. In other words, you handle the error first, which is fine.
For Options however, you handle the Some value before the None value. In other words, you handle the "error" last.

I understand this would mean a lot of refactoring for a lot of people, but I think this is more intuitive on the long-term.

**Comment by RandalSchwartz** [comment]
Even though this is a breaking change, it can't fail silently, and that's a good thing.
