### ISSUE TITLE
list extension mis-typed(?) return values

### ISSUE THREAD

**Issue by RandalSchwartz** [SandroMaglione/fpdart#65]
I was looking at the "List" extension, and I see this:

```
  /// Insert element `t` at the beginning of the [Iterable].
  Iterable<T> prepend(T t) => [t, ...this];
```

The return value is not an Iterable.  It's a List.  You *could* turn this function into an iterable with something like

```
    Iterable<T> prepend(T t) sync * { yield t; yield this* };
```
I just think it'd be more honest, and better for intellisense if things that are by necessity returning a List say so.  After all, you can call sort() on this output, but not with an Iterable, only if it's tagged as a List.

Put another way, if we could keep Iterable to mean "might be infinite", it'd be possible to construct some very cool function applications!

Edit: Idea... you could have both an iterable extension and a list extension, properly typing the function inputs!

Edit 2: On discord, we've just demonstrated that Dart picks the most restrictive type in the case of identical signatures:
```
extension<T> on Iterable<T> {
  void hello() => print('Hello from Iterable extension');
}

extension<T> on List<T> {
  void hello() => print('Hello from List extension');
}

void main() {
  List<String> list = [];
  list.hello(); // Hello from List extension

  Iterable<String> iterable = list;
  iterable.hello(); // Hello from Iterable extension
}
```

**Comment by SandroMaglione** [comment]
Hi @RandalSchwartz 

I agree. Indeed, the `list_extension` has a good margin for improvement, both in terms of typing and performance.

It's a good idea having a `list_extension` and `iterable_extension`. Adding this as a future improvement.

If you have some time, feel free also to send a PR if you have already some implementation in mind 👍

**Comment by RandalSchwartz** [comment]
I've been reading a lot of things about functional programming recently... this sequence was fascinating: https://fsharpforfunandprofit.com/posts/elevated-world/  as in I think I'm almost understanding most of the more esoteric definitions and terms, so I might actually be able to help out!  Don't wait for me though... you're really on a roll.

I have a pet project to map RiverPod's AsyncValue<T> type to possibly an Option<Either<Error, T>> or maybe an Either<Error,Option<T>>.  I'd have to make adaptors in both directions to allow existing RiverPod code to interoperate with fpdart.  Am I insane for wanting to do that? :)

**Comment by RandalSchwartz** [comment]
Lemme look in the next week to see if I have an hour or two to split everything that can be on an iterable to an iterable extension, and everything that requires a list to be on a list extension.  That'd be a good start toward creating iterable streams when possible, like my example above.
