### ISSUE TITLE
Question about tryCatch

### ISSUE THREAD

**Issue by ykaito21** [SandroMaglione/fpdart#68]
Hi, I have a question, as I am quite new to Functional programming and even imperative programming too.

Let's say I have something like this
```
class FirstException implements Exception {}

class SecondException implements Exception {}

class Student {
  final String name;
  Student(this.name);
}

class StudentRepo {
  static Future<List<Student>> getAllStudents() async => [
        Student('Juan'),
        Student('Maria'),
      ];
}
```

The question is how to handle only particular exception with `tryCatch`.
In this case, I want to throw exception other than FirstException and SecondException because I heard catching all exceptions and errors are not good practice.  But I am not sure how to handle this with functional way.

**Imperative way:**
```
Future<Either<String, List<Student>>> imperative() async {
  try {
    final students = await StudentRepo.getAllStudents();
    return right(students);
  } on FirstException {
    return left('FirstException');
  } on SecondException {
    return left('SecondException');
  }
  // I want to throw exception other than FirstException and SecondException
  // I want to avoid catch all exceptions without on clause
  // catch (e) {
  //   print(e);
  // }
}
```

**Functional way:**
```
TaskEither<String, List<Student>> getStudents = TaskEither.tryCatch(
  () => StudentRepo.getAllStudents(),
  (e, s) => // how to handle exception here?
);
```

Sorry, I may have misunderstood the concept of functional programming and this may be a dumb question.
Anyway, thank you for creating this wonderful package and very detailed documentation.

**Comment by SandroMaglione** [comment]
Hi @ykaito21 

Thanks for the question, which is indeed not obvious at all ☝️

`tryCatch` by design **catches all exceptions**. In functional programming we want to avoid throwing an exception, and instead use `Either` to return a value as error.

What I suggest is to change the return type to the following:
```dart
/// From [String] to [Exception] 👇
TaskEither<Exception, List<Student>> getStudents
``` 

Then inside `tryCatch` you can return your custom `Exception`:
```dart
TaskEither<Exception, List<Student>> getStudents = TaskEither.tryCatch(
  () => StudentRepo.getAllStudents(),
  (e, s) => e is FirstException ? FirstException() : e is SecondException ? SecondException() : Exception(),
);
```

When you then call `getStudents`, you can decide to throw somewhere else in the code if you find some unexpected exception:
```dart
final result = await getStudents.run();
/// if `result` contains `Exception`, then something is wrong, use `throw`
``` 

The general idea is to **not** throw and instead return a valid value, then later on in the code use `throw` if the returned value is something unexpected.

Does this answer your question?

**Comment by ykaito21** [comment]
Sorry for the confusing question.

> `tryCatch` by design **catches all exceptions**. In functional programming we want to avoid throwing an exception, and instead use `Either` to return a value as error.

I understand it.
The reason I asked this question is because Resocoder said [catching all exceptions are not ideal](https://youtu.be/NoZde-wYGA4?t=549), and he tried to avoid it by adding `try catch` in this [video](https://youtu.be/ZTU-WWEOoII?t=1551) (he is using darz package not fpdart). 

This is his code and [link](https://resocoder.com/2019/12/14/functional-error-handling-in-flutter-dart-2-either-task-fp/).
```
await Task(() => _postService.getOnePost())
    .attempt()
    // Grab the inner 'SomeType' held inside a Task<SomeType>
    // In this case, we get Either<Object, Post>
    .map(
      // Grab only the *left* side of Either<Object, Post>
      (either) => either.leftMap((obj) {
        try {
          // Cast the Object into a Failure
          return obj as Failure;
        } catch (e) {
          // 'rethrow' the original exception
          throw obj;
        }
      }),
    )
    .run()
    .then((value) => _setPost(value));
```
So I wanted to know if you have a similar idea for handling unexpected exceptions.
This may simply be a matter of taste and not pure functional programming.

I understand your idea.
Thank you for your detailed explanation and quick reply.

**Comment by SandroMaglione** [comment]
@ykaito21 the approach used in the video is not completely functional, and in fact it loses some of the advantages of a pure functional approach.

What I suggest instead is to define a function that returns `TaskEither` which **never throws**.

When you then call this function using `run` (somewhere else in the code), you can check if the result is `Left` (meaning an error from the `Either` type), and if the error is something unexpected you can decide to throw later if necessary:
1. `getStudents` (returns `TaskEither`, **no throw**)
2. `run()` after calling `getStudents`
3. if result is `Left`, handle failure case (_you could throw here if you get an unexpected exception_)

All of these is condensed in one function in the video.

Does this solve your doubts?

**Comment by ykaito21** [comment]
I got it! Thanks for the detailed explanation!
