### ISSUE TITLE
Can I use `Option.map` for side effect?

### ISSUE THREAD

**Issue by todd-kim** [SandroMaglione/fpdart#69]
Hello!
First of all, Thank you for your amazing work!
I'm using fpdart with flutter. I have a quick question. Can I use `Option.map` for side effect?
I think It will be working. But I'm not sure that.

```dart
final optionValue = Option.of(true);
optionValue.map((value) {
  print(value);
})
```

As the [examples](https://github.com/SandroMaglione/fpdart#option) for Option. It's better that use `match` for side effect. But I don't need a `None` case. 

```dart
final optionValue = Option.of(true);
optionValue.match(
  () => null,
  (value) => print(value),
);
```

Which one is better?

**Comment by SandroMaglione** [comment]
Hi @todd-kim 

In general, **you should not use `map` for side effects**. That's because the objective of `map` is to change the value inside `Option`, and nothing else.

Using `match` works. `match` in fact is designed for side effects: it's used to handle the result of `Option` **at the end of a chain**.

> **Note**: **Only** at the end of the chain. For side effects in the middle of a chain, take a look at [IO](https://pub.dev/documentation/fpdart/latest/fpdart/IO-class.html)

If you do not want to handle the `None` case, the cleanest way would be the following:
```dart
final optionValue = Option.of(true);
if (optionValue is Some) {
  print(optionValue.value);
}
```

Does this work for your usecase?

**Comment by ju851zel** [comment]
@SandroMaglione could you elaborate how you would run a side effect function in the middle of a chain with the help of `IO`?

I often have the use case that something returns an Either and I want the left case to be logged and convert it to an optional to use further.

Functionality wise I want something like that but without misusing map for the side effect:
```dart
Either<Exception, Uri> either = restService
      .getUrl(filePath: imagePath)
      .mapLeft(
        (final Exception exception) {
          log(exception);
          return exception;
        },
      );
return either.toOption();
```

I think something like that would be nice:

```dart
Either<Exception, Uri> either = restService
      .getUrl(filePath: imagePath)
      .runSideEffect(
        onLeft: (final Exception exception) => log(exception)
      );
return either.toOption();
```

 what do you think? Would you appreciate something like that then I would create an PR.

**Comment by SandroMaglione** [comment]
Hi @ju851zel 

Working with possible side effects requires more than just `Either` (or `Option`). `Either` should not include side effects at all, it should be a pure function from start to end.

When any side effect is introduced, then you need to use `IO`. In this case, `fpdart` has an `IOEither` class used for `IO` (side effects) that may fail (`Either`). Therefore, the result of the function must become `IOEither`.

```dart
Either<Exception, Uri> either /// ⛔️
IOEither<Exception, Uri> ioEither /// 👍
```

That being said, `fpdart` is currently missing a good API for your usecase. You need something that runs _on left_, but ignores the result, and continues with the chain.

`fpdart` has this method for `Right`, called `chainFirst`, but it’s missing it for `Left`. Currently you can do it like this:
```dart
IOEither<Exception, Uri> either = restService
    .getUrl(filePath: imagePath)
    .toIOEither()
    .swap()
    .chainFirst(
      (b) => IOEither.fromIO(
        IO(() {
          log(b);
        }),
      ),
    )
    .swap();
```

Ideally you would need a function like `chainFirst`, but that gives you the left value (`orElseFirst`):
```dart
IOEither<Exception, Uri> either = restService
    .getUrl(filePath: imagePath)
    .toIOEither()
    .orElseFirst<Exception>(
      (exception) => IOEither.fromIO(
        IO(() {
          log(exception);
          return exception;
        }),
      ),
    );
```

```dart
IOEither<L, R> orElseFirst<C>(IOEither<L, C> Function(L l) chain)
```

Does this work for your usecase?

**Comment by ju851zel** [comment]
Hi yes this does work for my use case. I was looking for something like `chainFirst`.

Logic wise this code is absolutely correct and doesn't misuse Either for side effects which I really like. 
But just for logging purposes the code looks a bit too complicated to be used at many places therefore I created an extension function for my purpose.
(Haven't fully tested and optimised it yet but it compiles)

```dart
extension IOExtension<L, R> on IOEither<L, R> {

  IOEither<L, R> runSideEffect<C>({
    final void Function(L l)? onLeft,
    final void Function(R r)? onRight,
  }) =>
      flatMap<R>(
        (final R r) => IOEither<R, void>.fromIO(
          IO<void>(() => onRight?.call(r)),
        ).flatMap((final _) => IOEither<R, L>.left(r)).swap(),
      )
          .swap()
          .flatMap<L>(
            (final L exception) => IOEither<L, void>.fromIO(
              IO<void>(() => onLeft?.call(exception)),
            ).flatMap((final _) => IOEither<L, R>.left(exception)).swap(),
          )
          .swap();
}
```

and this enables me to do the following:

```dart
IOEither<Exception, Uri>.fromEither(
      restService.getUrl(filePath: imagePath),
    )
        .runSideEffect(
          onRight: (final Uri uri) => debugPrint(uri.toString()),
          onLeft: (final Exception exception) => debugPrint(exception.toString()),
        )
        .run()
        .toOption();
```

I couldn't find the `toIOEither()` on the Either<L,R> but only a `toTaskEither()` but I can add that as an extension function too.

Thanks again for the help and clarifications on IO  💚

**Comment by SandroMaglione** [comment]
@ju851zel this looks awesome, you have a really good understanding of how functional programming and `fpdart` work 🤩

Some suggestions:
- You do not need the generic parameter `C`
- When you do not need the value of `flatMap` (`flatMap((_) => ...`) you can use [`andThen`](https://pub.dev/documentation/fpdart/latest/fpdart/IOEither/andThen.html)
- You do not need to declare the type of parameters like `final R r`, you can simply say `r` and the type is inferred
- If you are using `flatMap`, but then converting back to the original value, this is the perfect usecase for `chainFirst`
- `toIOEither()` is coming in the next version of `fpdart` 🔜

Here below 2 alternative implementation with `andThen` and `chainFirst`, let me know if these work for you: 

```dart
extension IOExtension<L, R> on IOEither<L, R> {
  IOEither<L, R> runSideEffect({
    final void Function(L l)? onLeft,
    final void Function(R r)? onRight,
  }) =>
      flatMap<R>(
        (r) => IOEither<R, void>.fromIO(
          IO<void>(() => onRight?.call(r)),
        ).andThen(() => IOEither<R, L>.left(r)).swap(),
      )
          .swap()
          .flatMap<L>(
            (exception) => IOEither<L, void>.fromIO(
              IO<void>(() => onLeft?.call(exception)),
            ).andThen(() => IOEither<L, R>.left(exception)).swap(),
          )
          .swap();

  IOEither<L, R> runSideEffectChainFirst({
    final void Function(L l)? onLeft,
    final void Function(R r)? onRight,
  }) =>
      chainFirst(
        (r) => IOEither<L, void>.fromIO(
          IO(() => onRight?.call(r)),
        ),
      )
          .swap()
          .chainFirst(
            (r) => IOEither<R, void>.fromIO(
              IO(() => onLeft?.call(r)),
            ),
          )
          .swap();
}
```

```dart
IOEither<String, int>.of(10)
    .runSideEffectChainFirst(onLeft: print, onRight: print)
    .run();
```

**Comment by ju851zel** [comment]
This looks awesome and I will definetely use the `runSideEffectChainFirst` because it is even shorter.
