### ISSUE TITLE
Small nitpick with the divide examples

### ISSUE THREAD

**Issue by jcdang** [SandroMaglione/fpdart#71]
https://github.com/SandroMaglione/fpdart/blob/2c8cdd73f7d774a18d806743357a77f7569726d6/example/src/option/overview.dart#L4-L10

This is kind of a red herring but I still wanted to address it.  Floating point division by zero is not really breaking.
```dart
void main() {
  final allPassed = [
      double.nan != double.nan,
      !double.infinity.isNaN,
      !double.negativeInfinity.isNaN,
      (0 / 0).isNaN,
      (1 / 0) == double.infinity,
      (-1 / 0) == double.negativeInfinity,
  ].every((x) => x);
  print('All True: $allPassed'); // Output: All True: true
}

```

A better example that definitely breaks:
```dart
int divide(int a, int b) => a ~/ b;
divide(10, 0); // Unhandled exception:  IntegerDivisionByZeroException
```

**Comment by SandroMaglione** [comment]
Hi @jcdang 

You are right, thanks for pointing this out 👍. Would you be open to send a PR to fix this?
