### ISSUE TITLE
catch only specified exceptions vs all

### ISSUE THREAD

**Issue by jcdang** [SandroMaglione/fpdart#73]
I'd have to go check the semantics of the other libraries but it would be nice to have distinctions of:
try-catch for all vs for specific types

Cats has helpers for nonFatal but I'm not sure how it will work given dart lets you throw and catch everything under the sun.

One option is to follow Dart's Future  with an optional test function.
```dart
// from async/future.dart
Future<T> catchError(Function onError, {bool test(Object error)?});
```

Another option is to specify it via type
```dart
class Test {
  static void catchOnly<T>(void Function() fn, void Function(T) onError) {
    try {
      fn();
    } on T catch(e) {
      onError(e);
    }
  }
}

main() {
  fnHandlerInt(int e) => print('Handling int: $e');
  fnHandlerError(Error e) => print('Handling Error: $e');

  print("1");
  Test.catchOnly(() => throw 1, fnHandlerInt);
  print('2');
  Test.catchOnly(() => 1 ~/ 0, fnHandlerError);
  print('3');
  Test.catchOnly(() => throw 1, fnHandlerError); // Uncaught Error
  print('4'); // unreachable
  // Output:
  // 1
  // Handling int: 1
  // 2
  // Handling Error: Unsupported operation: Result of truncating division is Infinity: 1 ~/ 0
  // 3
  // Uncaught Error: 1
}
```

It rarely a good idea to catch everything but the dart language doesn't offer classifications from a overflow/OOM versus a parsing error.  A possible workout is to explicitly enumerate all the fatal errors and re-throw them immediately.
Thoughts?

**Comment by SandroMaglione** [comment]
Hi @jcdang 

The issue with the `void Function(T) onError` function is that it allows you to catch only one type `T`, while users generally want to specify any number of different types.

I generally suggest to use `tryCatch` in these cases, and check the type of `Object` in the `onError` function:
```dart
TaskEither.tryCatch(
  ... /// Operation that may fail
  (obj, _) {
    if (obj is ErrorTypeToCheck) ...
  }
```

You can then decide to [throw later on in the code if you map `obj` to some unexpected error.](https://github.com/SandroMaglione/fpdart/issues/68#issuecomment-1324577954)
