### ISSUE TITLE
Difference between `IOEither` and `Either`

### ISSUE THREAD

**Issue by haashem** [SandroMaglione/fpdart#74]
Can you give an example to showcase difference between two? I can use both `IOEither` and `Either ` in `synchronous` operations. So I can say they are same? may I see a use case?

**Comment by SandroMaglione** [comment]
Hi @haashem 

The difference between `IOEither` and `Either` is that `IOEither` is designed for handling **synchronous side effects**, while `Either` is not supposed to run any side effect at all.

An example would be reading and validating a user input:
```dart
/// No side effects, [Either]
Either<String, String> validateUserInput(String? userInput) => userInput
    .toEither(
      () => "Missing user input",
    )
    .flatMap(
      (str) => str.isEmpty ? Either.left("Empty input") : Either.of(str),
    );

/// IO side effect, [IOEither]
IOEither<String, String> getAndValidateUserInput = IOEither(() {
  final line = stdin.readLineSync(); /// 👈 Side effect
  return validateUserInput(line);
});
```

- As you can see, **the validation itself** does not include any side effect: it only takes a `String?` and returns an `Either`, without any IO event or external request (no side effects)
- On the other hand, **getting the user input** requires an IO event, which is a side effect. Therefore this operation requires to convert `Either` to `IOEither`

Let me know if this example is clear to understand the difference.
