### ISSUE TITLE
change match/fold extension for bools to named parameters

### ISSUE THREAD

**Issue by thomrad** [SandroMaglione/fpdart#75]
Hi!

I just found out, that match (and fold) for booleans exist. Which is nice and I prefer it over the ternary operator. What I have troubles with, is to distinct between true and false. Sure, you get used to it, if used more often, but at first, I didn't know which is which, since there are actually parameterless functions to provide as paramters.

So my suggestion would be, use named parameters.

Like so:

`true.match(onFalse: () => 'it is false', onTrue: () => 'it is true');`

I use the match function, if I want to continue with the return value for more functional stuff.

Like so:

`result.match(() => something(), () => somethingdifferent()).morestuff()`

Feels better then this:

`(result ? something() : somethingdifferent()).morestuff()`

BTW, a very nice library, coming from F# to flutter/dart, it feels just like home 😄 

cheers, Thomas

**Comment by RandalSchwartz** [comment]
They're both required parameters though, and it mimics the other interfaces that require callbacks for both "sides" of a class.  I'd rather not type more.  I can also use aBool.match(whenFalse,whenTrue) if I have the function names, which is a nicely compact notation, similar to anEither(whenLeft,whenRight) or anOption(whenNone,whenSome).

**Comment by SandroMaglione** [comment]
Hi @thomrad 

As @RandalSchwartz says, the `match` extension for `boolean` mimics the same definition of types like `Option` and `Either`. This is mostly a convention which makes writing code more concise.

Furthermore, [pattern matching is coming](https://github.com/dart-lang/language/issues/546). This will give dart a native way of matching over patterns, possibly causing `match` in fpdart to become deprecated.

Closing this then, let me know if you have any further question.
