### ISSUE TITLE
Show example in docs of mixing functional packages and renaming classes

### ISSUE THREAD

**Issue by RandalSchwartz** [SandroMaglione/fpdart#76]
I wrote this recently for a customer:

```dart
/// This file is used to export all the functional programming libraries used in
/// the project. It also exports the [FpState] type alias, which is used to
/// avoid conflicts with the [State] class from the Flutter SDK.
///
import 'package:fpdart/fpdart.dart' as fpdart show State;

/// The `fpdart` library is used to create functional programming constructs.
export 'package:fpdart/fpdart.dart' hide State;

/// The `tuple` library is used to create tuples, which are immutable lists of
/// fixed length.
export 'package:tuple/tuple.dart' show Tuple3, Tuple4, Tuple5, Tuple6, Tuple7;

/// A type alias for the [State] class from the `fpdart` library.
typedef FpState<S, A> = fpdart.State<S, A>;
```

which we then put in `lib/core/functional.dart` and include that instead of fpdart or tuple.  It's a handy way to show how to rename the classes that conflict with other SDK or third-party packages.  Maybe this could go somewhere in the docs, or in one of the examples?  It'd also be a great place to add extensions to fpdart's types, so it'd need only one include for the project.

**Comment by SandroMaglione** [comment]
Hi @RandalSchwartz 

This looks great! Would you mind opening a PR for this? You can create and example project inside [`example`](https://github.com/SandroMaglione/fpdart/tree/main/example), showing how to setup and use this approach.

**Comment by RandalSchwartz** [comment]
Yah, lemme see if I can whip something up in the next few days.  The code is written... just need full examples that are independent of $client's private code.
