### ISSUE TITLE
Suggestion: Don't use factories for constructors

### ISSUE THREAD

**Issue by tim-smart** [SandroMaglione/fpdart#8]
One thing that was great about dartz was the ability to pass Option constructors directly to methods.

For example with dartz you could do this:

```dart
futureThatReturnsNullable.then(optionOf);
```

But you wouldn't be able to pass `Option.fromNullable` in this case.

**Comment by SandroMaglione** [comment]
Hi @tim-smart 

`optionOf` of `dartz` is not actually a constructor. [If you take a look at the implementation](https://github.com/spebbe/dartz/blob/2de2f2787430dcd4ef49485bbf8aac1f8d1ff157/lib/src/option.dart#L210), `optionOf` is an external function that initializes an `Option` from a nullable value.

I [added both `option` and `optionOf` to fpdart](https://github.com/SandroMaglione/fpdart/blob/c9b78aef0661a4ada306306e05b96da93bc652b4/lib/src/option.dart#L27) in the last commit. Thanks for the suggestion 👍

**Comment by tim-smart** [comment]
Thanks!

By constructor, I mean it constructs a new instance of `Option`.

You could potentially use static methods instead of factory.
