### ISSUE TITLE
Either of void

### ISSUE THREAD

**Issue by bhoudebert** [SandroMaglione/fpdart#83]
Hello there,

Still a rookie in Dart, I need to do something like this:  `Either<MyError, void>`. I usually use this in real FP language (Haskell or even Rust)

At signature level, it is fine but I do not find the way to write `Either.right(void)` (which does not compile obviously.

Any hint?

In the mean time I am using a Unit/Void specific homemade object but this does not look so nice.

**Comment by AdamHavlicek** [comment]
have you tried `Either<MyError, void>.right(null)`?

**Comment by bhoudebert** [comment]
> have you tried `Either<MyError, void>.right(null)`?

Ok it definitely work, thanks, did not know null would be considered as void.

**Comment by AdamHavlicek** [comment]
> > have you tried `Either<MyError, void>.right(null)`?
> 
> Ok it definitely work, thanks, did not know null would be considered as void.

![image](https://user-images.githubusercontent.com/50631920/216781579-fe3fdc98-6633-4309-8420-2202fc3e0130.png)
