### ISSUE TITLE
Option losing alt and foldable

### ISSUE THREAD

**Issue by RandalSchwartz** [SandroMaglione/fpdart#94]
I see on master that Option is losing alt and foldable... what's up with that?

**Comment by SandroMaglione** [comment]
Hi @RandalSchwartz 

In order to support `const` for `None` (`const factory`) it was necessary to use `Never`. This in turn required dropping some type classes.

You can check the discussion [in the PR here](https://github.com/SandroMaglione/fpdart/pull/92).
