### ISSUE TITLE
Issue: Version 0.4.1 creates Type Exception on getOrElse

### ISSUE THREAD

**Issue by ju851zel** [SandroMaglione/fpdart#95]
I noticed when using 0.4.1 in contrast to 0.4.0 a type exception is thrown when using `getOrElse` on `Option`.

```dart
type '() => String' is not a subtype of type '() => Never' of 'orElse'
```

The code responsible for the error is: 
```dart
model.activeProfile
           .map((final Profile profile) => profile.isActive)
           .getOrElse(() => false)
```

Is this a known issue? Downgrading to Version `0.4.0` from `0.4.1` works.

**Comment by ju851zel** [comment]
@SandroMaglione Can you elaborate what the issue exactly was? I tried to understand the PR but it just seems to change dependency versions.

**Comment by SandroMaglione** [comment]
@ju851zel you can read details in #92 

The issue was with introducing a `const factory` constructor for `None`. When calling `map`, it caused the type to be wrong at runtime.

**Comment by qwertylolman** [comment]
well, it's not fixed. i got 
type '() => TaskEither<L, R>' is not a subtype of type '() => TaskEither<L, Never>' of 'orElse'<…>
